architect:
  - amihaiemil
docker:
  as_root: true
env:
  MAVEN_OPTS: "-XX:MaxPermSize=256m -Xmx1g"
merge:
  script: |-
    mvn clean install
deploy:
  script:
   #- echo "Any deployment script here..."
   - sudo mkdir ~/.ssh
   - sudo ssh-keyscan -H github.com >> ~/.ssh/known_hosts
   - cd ..
   - sudo git clone git@github.com:amihaiemil/amihaiemil.github.io.git
   - cd amihaiemil.github.io
   - pwd
decrypt:
  settings.xml: "repo/rcfg/settings.xml.asc"
  pubring.gpg: "repo/rcfg/pubring.gpg.asc"
  secring.gpg: "repo/rcfg/secring.gpg.asc"
release:
  script: |-
    chmod +x ./rrv.sh
    ./rrv.sh
